// ========================================
// GAME STATE MANAGER
// ========================================
// Centralized game state management for multiplayer support.
// Separates core game state from UI state and provides event-driven updates.

import { gameEngine, startingDecklist } from '../logic/gameLogic.js';
import ActionProcessor from './ActionProcessor.js';
import GameDataService from '../services/GameDataService.js';
import fullDroneCollection from '../data/droneData.js';
import { initializeDroneSelection } from '../utils/droneSelectionUtils.js';
import { debugLog } from '../utils/debugLogger.js';
import { starterPoolCards, starterPoolDroneNames } from '../data/saveGameSchema.js';
import { convertComponentsToSectionSlots } from '../logic/migration/saveGameMigrations.js';
import { ECONOMY } from '../data/economyData.js';
import { generateMapData } from '../utils/mapGenerator.js';
import CombatOutcomeProcessor from '../logic/singlePlayer/CombatOutcomeProcessor.js';
import { shipComponentCollection } from '../data/shipSectionData.js';
import { getAllShips, getDefaultShip } from '../data/shipData.js';
import { calculateSectionBaseStats } from '../logic/statsCalculator.js';
import fullCardCollection from '../data/cardData.js';
import ReputationService from '../logic/reputation/ReputationService.js';
import { calculateExtractedCredits } from '../logic/singlePlayer/ExtractionController.js';
import { generateRandomShopPack } from '../data/cardPackData.js';
import aiPhaseProcessor from './AIPhaseProcessor.js';
import tacticalMapStateManager from './TacticalMapStateManager.js';
import transitionManager from './TransitionManager.js';
import StateValidationService from '../logic/state/StateValidationService.js';
import GuestSyncManager from './GuestSyncManager.js';
import SinglePlayerInventoryManager from './SinglePlayerInventoryManager.js';
import TacticalItemManager from './TacticalItemManager.js';

class GameStateManager {
  constructor() {
    debugLog('STATE_SYNC', '🔄 GAMESTATE INITIALIZATION: Creating new GameStateManager instance');

    // Event listeners for state changes
    this.listeners = new Set();

    // State validation service (extracted — validates state updates, phase transitions, ownership)
    this.stateValidationService = new StateValidationService(this);

    // Core application state (minimal until game starts)
    this.state = {
      // --- APPLICATION STATE ---
      appState: 'menu', // 'menu', 'inGame', 'gameOver'

      // --- MULTIPLAYER STATE ---
      isConnected: false,
      opponentId: null,
      gameMode: 'local', // 'local', 'host', 'guest'

      // --- TESTING MODE ---
      testMode: false, // Indicates if this is a test game (bypasses normal flow)

      // --- GAME STATE (null until game starts) ---
      gameActive: false,
      gameSeed: null, // Random seed for deterministic gameplay (generated by Host/Local, received by Guest)
      turnPhase: null,
      turn: null,
      currentPlayer: null,
      actionsTakenThisTurn: 0,  // Track actions for NOT_FIRST_ACTION ability condition
      firstPlayerOfRound: null,
      firstPasserOfPreviousRound: null,
      firstPlayerOverride: null,
      passInfo: null,
      winner: null,
      player1: null,
      player2: null,
      placedSections: [],
      opponentPlacedSections: [],
      unplacedSections: [],
      shieldsToAllocate: 0,
      droneSelectionPool: [],
      droneSelectionTrio: [],
      gameLog: [],
      aiDecisionHistory: [], // Array of AI decision entries for CSV export

      // --- GAME FLOW METADATA (owned by GameFlowManager) ---
      gameStage: 'preGame', // 'preGame', 'roundLoop', 'gameOver'
      roundNumber: 0,

      // --- COMMITMENTS (for simultaneous phases) ---
      commitments: {},

      // --- SINGLE-PLAYER STATE (Extraction Mode) ---
      singlePlayerProfile: null,         // Player profile data
      singlePlayerInventory: {},         // Card inventory (master quantities)
      singlePlayerDroneInstances: [],    // Drone instances with damage tracking
      singlePlayerShipComponentInstances: [],  // Ship component instances with hull tracking
      singlePlayerDiscoveredCards: [],   // Card discovery states (owned/discovered/undiscovered)
      singlePlayerShipSlots: [],         // 6 ship slots
      quickDeployments: [],              // Quick deploy templates (max 5)

      // --- EXTRACTION DECK BUILDER NAVIGATION ---
      extractionDeckSlotId: null,        // Slot ID being edited (0-5) or null
      extractionNewDeckOption: null,     // 'empty' | 'copyFromSlot0' | null

      // --- FAILED RUN LOADING SCREEN ---
      showFailedRunScreen: false,        // Show failed run transition screen
      failedRunType: null,               // 'combat' | 'detection' | 'abandon'
      failedRunIsStarterDeck: false,     // If true, show "RUN FAILED" instead of "SHIP MARKED MIA"
    };

    // Initialize action processor using singleton pattern
    // PhaseAnimationQueue will be injected later in AppRouter
    this.actionProcessor = ActionProcessor.getInstance(this, null);

    // Game flow manager reference (set during initialization)
    this.gameFlowManager = null;

    // Guest sync manager (extracted — handles P2P integration, optimistic actions, host state)
    this.guestSyncManager = new GuestSyncManager(this);

    // Single-player inventory manager (extracted — save/load, inventory, card discovery, ship components)
    this.singlePlayerInventoryManager = new SinglePlayerInventoryManager(this);

    // Tactical item manager (extracted — item purchase/use, card pack shop)
    this.tacticalItemManager = new TacticalItemManager(this);

    // Context flag for production-safe validation (avoids minification breaking stack traces)
    this._updateContext = null;

    // Log initial application state
    debugLog('STATE_SYNC', '🔄 GAMESTATE INITIALIZATION: GameStateManager created');
    debugLog('STATE_SYNC', '📱 App State:', this.state.appState);
    debugLog('STATE_SYNC', '🎮 Game Active:', this.state.gameActive);
    debugLog('STATE_SYNC', '✅ GAMESTATE INITIALIZATION: GameStateManager ready (no game active)');
  }

  // --- MANAGER REFERENCES ---

  /**
   * Set the GameFlowManager reference
   * @param {Object} gameFlowManager - GameFlowManager instance
   */
  setGameFlowManager(gameFlowManager) {
    this.gameFlowManager = gameFlowManager;
  }

  // --- GUEST SYNC FACADES ---
  // GFM and GMQS access these via this.gameStateManager — thin delegation to guestSyncManager
  // TODO: Remove facades when GFM/GMQS are updated to receive guestSyncManager directly

  setupP2PIntegration(p2pManager) { this.guestSyncManager.setupP2PIntegration(p2pManager); }
  startValidation(targetPhase, guestState) { this.guestSyncManager.startValidation(targetPhase, guestState); }
  shouldValidateBroadcast(incomingPhase) { return this.guestSyncManager.shouldValidateBroadcast(incomingPhase); }
  isMilestonePhase(phase) { return this.guestSyncManager.isMilestonePhase(phase); }
  applyHostState(hostState) { this.guestSyncManager.applyHostState(hostState); }
  trackOptimisticAnimations(animations) { this.guestSyncManager.trackOptimisticAnimations(animations); }
  filterAnimations(actionAnimations, systemAnimations) { return this.guestSyncManager.filterAnimations(actionAnimations, systemAnimations); }
  hasRecentOptimisticActions() { return this.guestSyncManager.hasRecentOptimisticActions(); }
  clearOptimisticActions() { this.guestSyncManager.clearOptimisticActions(); }

  // --- EVENT SYSTEM ---

  /**
   * Subscribe to state changes
   * @param {Function} listener - Callback function called when state changes
   * @returns {Function} Unsubscribe function
   */
  subscribe(listener) {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  /**
   * Notify all listeners of state change
   * @param {string} type - Type of change
   * @param {Object} payload - Additional data
   */
  emit(type, payload = {}) {
    this.listeners.forEach(listener => {
      try {
        listener({ type, payload, state: this.getState() });
      } catch (error) {
        debugLog('STATE_SYNC', '🚨 Error in state listener', { error });
      }
    });
  }

  // --- STATE ACCESS ---

  /**
   * Get current state (read-only)
   */
  getState() {
    return { ...this.state };
  }

  /**
   * Get specific state property
   */
  get(key) {
    return this.state[key];
  }

  /**
   * Update state and notify listeners
   * @param {Object} updates - State updates to apply
   * @param {string} eventType - Type of event for logging
   * @param {string} context - Context of the update for validation (e.g., 'phaseTransition')
   */
  setState(updates, eventType = 'STATE_UPDATE', context = null) {
    const prevState = { ...this.state };

    // CRITICAL: Log appState transitions for extraction mode debugging
    if (updates.appState && updates.appState !== this.state.appState) {
      debugLog('EXTRACTION', 'appState transition', {
        from: this.state.appState,
        to: updates.appState,
        hasRunState: tacticalMapStateManager.isRunActive(),
        runAbandoning: this.state.runAbandoning,
        eventType
      });
    }

    // Extract caller information from stack trace for detailed logging
    const stack = new Error().stack;
    const stackLines = stack ? stack.split('\n') : [];
    const callerInfo = this.stateValidationService.extractCallerInfo(stackLines);

    // Check for architecture violations - App.jsx should NEVER directly update GameStateManager
    // However, App.jsx can call ActionProcessor/PhaseManager/ExtractionController which then update GameStateManager
    const isAppJsxCaller = stackLines.some(line => line.includes('App.jsx'));
    const isViaActionProcessor = stackLines.some(line => line.includes('ActionProcessor'));
    const isViaPhaseManager = stackLines.some(line => line.includes('PhaseManager'));
    const isViaExtractionController = stackLines.some(line => line.includes('ExtractionController'));
    const isLegitimateCall = isViaActionProcessor || isViaPhaseManager || isViaExtractionController;

    if (isAppJsxCaller && !isLegitimateCall) {
      debugLog('VALIDATION', '🚨 ARCHITECTURE VIOLATION: App.jsx is directly updating GameStateManager!', {
        recommendation: 'App.jsx should only call ActionProcessor, PhaseManager, or ExtractionController methods',
        stack
      });
    }

    // Comprehensive state change logging
    const updateKeys = Object.keys(updates);
    const caller = `${callerInfo.primaryCaller} in ${callerInfo.primaryFile}`;

    debugLog('STATE_SYNC', `🔍 GAMESTATE CHANGE [${eventType}] from ${caller}:`, {
      changedKeys: updateKeys,
      allUpdates: updates,
      architectureViolation: isAppJsxCaller && !isLegitimateCall
    });

    // Special detailed logging for player state changes (skip during initialization)
    const isInitializationEvent = ['GAME_RESET', 'INITIALIZATION'].includes(eventType);
    if ((updates.player1 || updates.player2) && !isInitializationEvent) {
      this.stateValidationService.logPlayerStateChanges(updates, prevState, caller, eventType);
    }

    // Log other critical state changes
    updateKeys.forEach(key => {
      if (!['player1', 'player2'].includes(key)) {
        const oldValue = prevState[key];
        const newValue = updates[key];
        if (JSON.stringify(oldValue) !== JSON.stringify(newValue)) {
          debugLog('STATE_SYNC', `🔍 STATE CHANGE: ${key}`, {
            before: oldValue,
            after: newValue,
            caller: caller,
            eventType: eventType
          });
        }
      }
    });

    // Validate state consistency before update
    this.stateValidationService.validateStateUpdate(updates, prevState, context);

    this.state = { ...this.state, ...updates };
    this.emit(eventType, { updates, prevState });
  }

  // --- GAME STATE METHODS ---

  /**
   * Validate that game state is clean before starting a new game
   * @returns {{ valid: boolean, issues: string[] }} Validation result
   */
  validatePreGameState() {
    const issues = [];

    if (this.state.gameStage !== 'preGame') {
      issues.push(`gameStage is '${this.state.gameStage}' (expected 'preGame')`);
    }
    if (this.state.roundNumber !== 0) {
      issues.push(`roundNumber is ${this.state.roundNumber} (expected 0)`);
    }
    if (this.state.gameActive) {
      issues.push('gameActive is true (expected false)');
    }
    if (this.state.player1 !== null) {
      issues.push('player1 is not null');
    }
    if (this.state.player2 !== null) {
      issues.push('player2 is not null');
    }
    if (this.state.turnPhase !== null) {
      issues.push(`turnPhase is '${this.state.turnPhase}' (expected null)`);
    }
    if (tacticalMapStateManager.isRunActive()) {
      issues.push('TacticalMapStateManager has active run (orphaned single-player run)');
    }
    if (this.state.singlePlayerEncounter !== null) {
      issues.push('singlePlayerEncounter is not null');
    }
    if (this.state.winner !== null) {
      issues.push(`winner is '${this.state.winner}' (expected null)`);
    }
    if (this.state.commitments && Object.keys(this.state.commitments).length > 0) {
      issues.push('commitments object is not empty');
    }

    if (issues.length > 0) {
      debugLog('STATE_SYNC', '⚠️ Pre-game state validation failed:', issues);
      return { valid: false, issues };
    }
    return { valid: true, issues: [] };
  }

  /**
   * Validate that state is clean before starting a single-player run
   * @returns {{ valid: boolean, issues: string[] }} Validation result
   */
  validatePreRunState() {
    const issues = [];

    if (tacticalMapStateManager.isRunActive()) {
      issues.push('TacticalMapStateManager has active run (run already in progress)');
    }
    if (this.state.singlePlayerEncounter !== null) {
      issues.push('singlePlayerEncounter is not null');
    }
    if (this.state.gameActive) {
      issues.push('gameActive is true (PvP game in progress)');
    }

    if (issues.length > 0) {
      debugLog('STATE_SYNC', '⚠️ Pre-run state validation failed:', issues);
      return { valid: false, issues };
    }
    return { valid: true, issues: [] };
  }

  /**
   * Clear single-player context (run state and encounter) without clearing profile/inventory
   * Call this before starting PvP games to clean up orphaned SP state
   */
  clearSinglePlayerContext() {
    debugLog('STATE_SYNC', '🧹 Clearing single-player context');
    // End run in TacticalMapStateManager if active
    if (tacticalMapStateManager.isRunActive()) {
      tacticalMapStateManager.endRun();
    }
    this.setState({
      singlePlayerEncounter: null
    });
  }

  /**
   * Safely transition to a new app state with automatic cleanup
   * @param {string} newState - The new app state to transition to
   */
  transitionToAppState(newState) {
    // Clean up active game if navigating away to menu
    if (this.state.gameActive && newState === 'menu') {
      debugLog('STATE_SYNC', 'Active game detected during navigation, cleaning up');
      this.endGame();
    }

    // Clean up run state if navigating to menu
    if (tacticalMapStateManager.isRunActive() && newState === 'menu') {
      debugLog('STATE_SYNC', 'Active run detected during navigation, cleaning up');
      this.endRun(false); // Lost run
    }

    this.setState({ appState: newState });
  }

  /**
   * Reset game to initial state
   */
  reset() {
    debugLog('STATE_SYNC', '🔄 GAME RESET: Resetting game state and clearing caches');

    const initialState = {
      turnPhase: 'preGame',
      turn: 1,
      currentPlayer: null,
      actionsTakenThisTurn: 0,
      firstPlayerOfRound: null,
      firstPasserOfPreviousRound: null,
      firstPlayerOverride: null,
      passInfo: { firstPasser: null, player1Passed: false, player2Passed: false },
      winner: null,
      player1: gameEngine.initialPlayerState('Player 1', startingDecklist),
      player2: gameEngine.initialPlayerState('Player 2', startingDecklist),
      placedSections: [],
      opponentPlacedSections: [],
      unplacedSections: [],
      shieldsToAllocate: 0,
      droneSelectionPool: [],
      droneSelectionTrio: [],
      gameLog: [],

      // --- COMMITMENTS (for simultaneous phases) ---
      commitments: {},
    };

    this.setState(initialState, 'GAME_RESET');

    // Clear GameDataService singleton and cache to prevent stale data
    GameDataService.reset();

    // Clear ActionProcessor queue to prevent stale actions
    this.actionProcessor.clearQueue();
    // Re-establish GameFlowManager's subscription after clearQueue wipes listeners
    this.gameFlowManager?.resubscribe();

    debugLog('STATE_SYNC', '✅ GAME RESET: State, cache, and queue cleared');
  }

  /**
   * Start a new game session - initialize players and game state
   * @param {string} gameMode - 'local', 'host', 'guest'
   * @param {Object} player1Config - Player 1 configuration
   * @param {Object} player2Config - Player 2 configuration
   */
  startGame(gameMode = 'local', player1Config = {}, player2Config = {}) {
    debugLog('STATE_SYNC', '🎮 GAME START: Initializing new game session');

    // Clear any orphaned single-player context before starting PvP
    this.clearSinglePlayerContext();

    // Validate pre-game state and cleanup if dirty
    const validation = this.validatePreGameState();
    if (!validation.valid) {
      debugLog('VALIDATION', '🚨 DIRTY STATE DETECTED AT GAME START', {
        issues: validation.issues,
        action: 'Calling resetGameState() to clean up',
        stack: new Error().stack
      });
      this.resetGameState();
    }

    // Generate random game seed for deterministic gameplay
    // Host/Local generates, Guest receives from first broadcast
    const gameSeed = gameMode === 'guest'
      ? null  // Guest will receive seed from Host
      : Math.floor(Math.random() * 2147483647);

    const gameState = {
      // Activate game
      appState: 'inGame',
      gameActive: true,
      gameMode: gameMode,
      gameSeed: gameSeed,

      // Initialize game flow
      turnPhase: 'deckSelection',
      turn: 1,
      gameStage: 'preGame',
      roundNumber: 0,
      currentPlayer: null,
      actionsTakenThisTurn: 0,
      firstPlayerOfRound: null,
      firstPasserOfPreviousRound: null,
      firstPlayerOverride: null,
      passInfo: { firstPasser: null, player1Passed: false, player2Passed: false },
      winner: null,

      // Initialize players with custom configurations
      player1: {
        ...gameEngine.initialPlayerState(
          player1Config.name || 'Player 1',
          player1Config.decklist || startingDecklist,
          'player1',
          gameSeed,  // Use same seed for both players
          player1Config.shipId || null  // Ship card ID (null = default)
        ),
        ...player1Config
      },
      player2: {
        ...gameEngine.initialPlayerState(
          player2Config.name || 'Player 2',
          player2Config.decklist || startingDecklist,
          'player2',
          gameSeed,  // Use same seed for both players
          player2Config.shipId || null  // Ship card ID (null = default)
        ),
        ...player2Config
      },

      // Initialize game components
      placedSections: [],
      opponentPlacedSections: [],
      unplacedSections: [],
      shieldsToAllocate: 0,
      gameLog: [],

      // --- COMMITMENTS (for simultaneous phases) ---
      commitments: {},

      // Drone selection data (will be initialized by GameFlowManager when transitioning to droneSelection)
      droneSelectionPool: [],
      droneSelectionTrio: [],
    };

    this.setState(gameState, 'GAME_STARTED');

    // Set up GameFlowManager subscription just before gameplay begins
    // This is the "just-in-time" initialization point for turn transitions
    // See: GameFlowManager.subscription.test.js for architectural documentation
    this.gameFlowManager?.resubscribe();

    debugLog('STATE_SYNC', '👤 Player 1 Created:', {
      name: gameState.player1.name,
      energy: gameState.player1.energy,
      deckCount: gameState.player1.deck?.length || 0
    });
    debugLog('STATE_SYNC', '👤 Player 2 Created:', {
      name: gameState.player2.name,
      energy: gameState.player2.energy,
      deckCount: gameState.player2.deck?.length || 0
    });
    debugLog('STATE_SYNC', '✅ GAME START: Game session initialized successfully');
  }

  /**
   * End current game session - return to menu state
   */
  endGame() {
    debugLog('STATE_SYNC', '🎮 GAME END: Ending current game session and clearing caches');

    // Use canonical reset function for all game state cleanup
    this.resetGameState();

    // Set app state to menu (not part of game state reset)
    this.setState({
      appState: 'menu',
    }, 'GAME_ENDED');

    // Clear GameDataService singleton and cache to prevent stale data in new games
    GameDataService.reset();

    // Clear ActionProcessor queue to prevent stale actions
    this.actionProcessor.clearQueue();
    // Re-establish GameFlowManager's subscription after clearQueue wipes listeners
    this.gameFlowManager?.resubscribe();

    // Reset GameFlowManager to clear phase state (includes PhaseManager.reset())
    if (this.gameFlowManager) {
      this.gameFlowManager.reset();
    }

    // Clean up AIPhaseProcessor (clear timers, unsubscribe from state changes)
    // This prevents stale subscriptions and timers from affecting the next game
    if (aiPhaseProcessor?.cleanup) {
      aiPhaseProcessor.cleanup();
      debugLog('STATE_SYNC', '✅ AIPhaseProcessor cleaned up');
    }

    debugLog('STATE_SYNC', '✅ GAME END: Returned to menu state, all singletons cleared');
  }

  /**
   * Initialize test mode game - bypasses normal game flow
   * @param {Object} testConfig - Test configuration from testGameInitializer
   * @returns {boolean} Success status
   */
  initializeTestMode(testConfig) {
    debugLog('STATE_SYNC', '🧪 TEST MODE: Initializing test game from GameStateManager');

    // Import testGameInitializer dynamically to avoid circular dependencies
    import('../services/testGameInitializer.js').then(module => {
      const success = module.initializeTestGame(testConfig, this);

      if (success) {
        debugLog('STATE_SYNC', '✅ TEST MODE: Test game initialized successfully');
      } else {
        debugLog('STATE_SYNC', '❌ TEST MODE: Test game initialization failed');
      }
    }).catch(error => {
      debugLog('STATE_SYNC', '🚨 TEST MODE: Error importing testGameInitializer', { error });
    });

    return true; // Return immediately, actual initialization happens asynchronously
  }

  /**
   * Set multiplayer mode and role
   */
  setMultiplayerMode(mode, isHost = false) {
    this.setState({
      gameMode: mode,
    }, 'MULTIPLAYER_MODE_SET');
  }

  /**
   * Update player states
   */
  updatePlayers(player1Updates = {}, player2Updates = {}) {
    const updates = {};
    if (Object.keys(player1Updates).length > 0) {
      updates.player1 = { ...this.state.player1, ...player1Updates };
    }
    if (Object.keys(player2Updates).length > 0) {
      updates.player2 = { ...this.state.player2, ...player2Updates };
    }

    if (Object.keys(updates).length > 0) {
      this.setState(updates, 'PLAYERS_UPDATED');
    }
  }

  /**
   * Update specific player state directly
   */
  updatePlayerState(playerId, updates) {
    if (playerId === 'player1') {
      this.updatePlayers(updates, {});
    } else if (playerId === 'player2') {
      this.updatePlayers({}, updates);
    }
  }

  /**
   * Set player states directly (for gameLogic integration)
   */
  setPlayerStates(newPlayer1, newPlayer2) {
    this.setState({
      player1: newPlayer1,
      player2: newPlayer2
    }, 'PLAYER_STATES_SET');

    // DEBUG: Log event emission timing
    debugLog('RESOURCE_RESET', `🔔 [GAMESTATEMANAGER] PLAYER_STATES_SET event emitted`, {
      timestamp: Date.now(),
      player1Energy: newPlayer1.energy,
      player1DeploymentBudget: newPlayer1.deploymentBudget,
      player2Energy: newPlayer2.energy,
      player2DeploymentBudget: newPlayer2.deploymentBudget
    });
  }

  /**
   * Set current player
   */
  setCurrentPlayer(playerId) {
    debugLog('TURN_TRANSITION_DEBUG', 'setCurrentPlayer called', {
      newPlayerId: playerId,
      previousPlayer: this.state.currentPlayer,
      subscriberCount: this.listeners.size
    });
    this.setState({ currentPlayer: playerId }, 'CURRENT_PLAYER_CHANGED');
  }

  /**
   * Set turn phase
   */
  setTurnPhase(phase) {
    this.setState({ turnPhase: phase }, 'TURN_PHASE_CHANGED');
  }

  /**
   * Set first player of round
   */
  setFirstPlayerOfRound(playerId) {
    this.setState({ firstPlayerOfRound: playerId }, 'FIRST_PLAYER_OF_ROUND_SET');
  }

  /**
   * Set first passer of previous round
   */
  setFirstPasserOfPreviousRound(playerId) {
    this.setState({ firstPasserOfPreviousRound: playerId }, 'FIRST_PASSER_OF_PREVIOUS_ROUND_SET');
  }

  /**
   * Set first player override
   */
  setFirstPlayerOverride(playerId) {
    this.setState({ firstPlayerOverride: playerId }, 'FIRST_PLAYER_OVERRIDE_SET');
  }

  /**
   * Update pass information
   */
  updatePassInfo(passUpdates) {
    const updatedPassInfo = { ...this.state.passInfo, ...passUpdates };
    this.setState({ passInfo: updatedPassInfo }, 'PASS_INFO_UPDATED');
  }

  /**
   * Set pass information directly
   */
  setPassInfo(passInfo) {
    this.setState({ passInfo: passInfo }, 'PASS_INFO_SET');
  }

  /**
   * Check if it's the local player's turn (for multiplayer)
   */
  isMyTurn() {
    // In local mode, player1 is the human player
    if (this.state.gameMode === 'local') return this.state.currentPlayer === 'player1';
    if (this.state.gameMode === 'host') return this.state.currentPlayer === 'player1';
    if (this.state.gameMode === 'guest') return this.state.currentPlayer === 'player2';
    return false;
  }

  /**
   * Get local player ID based on role
   */
  getLocalPlayerId() {
    if (this.state.gameMode === 'local') return 'player1'; // For local AI games
    if (this.state.gameMode === 'host') return 'player1';
    if (this.state.gameMode === 'guest') return 'player2';
    return 'player1';
  }

  /**
   * Get opponent player ID
   */
  getOpponentPlayerId() {
    const localId = this.getLocalPlayerId();
    return localId === 'player1' ? 'player2' : 'player1';
  }

  /**
   * Get local player state object
   */
  getLocalPlayerState() {
    const localId = this.getLocalPlayerId();
    return this.state[localId];
  }

  /**
   * Get opponent player state object
   */
  getOpponentPlayerState() {
    const opponentId = this.getOpponentPlayerId();
    return this.state[opponentId];
  }

  /**
   * Check if a given player ID is the local player (for UI perspective)
   */
  isLocalPlayer(playerId) {
    return playerId === this.getLocalPlayerId();
  }

  /**
   * Get placed sections for local player (UI perspective)
   */
  getLocalPlacedSections() {
    if (this.state.gameMode === 'local') return this.state.placedSections;
    if (this.state.gameMode === 'host') return this.state.placedSections;
    if (this.state.gameMode === 'guest') return this.state.opponentPlacedSections;
    return this.state.placedSections;
  }

  /**
   * Get placed sections for opponent (UI perspective)
   */
  getOpponentPlacedSections() {
    let result;
    if (this.state.gameMode === 'local') result = this.state.opponentPlacedSections;
    else if (this.state.gameMode === 'host') result = this.state.opponentPlacedSections;
    else if (this.state.gameMode === 'guest') result = this.state.placedSections;
    else result = this.state.opponentPlacedSections;

    // Only debug during placement phase when there's actual data
    if (this.state.turnPhase === 'placement' && result.some(s => s !== null)) {
      debugLog('STATE_SYNC', '🔍 [DEBUG] GameStateManager.getOpponentPlacedSections:', {
        gameMode: this.state.gameMode,
        result,
        rawOpponentPlacedSections: this.state.opponentPlacedSections,
        rawPlacedSections: this.state.placedSections
      });
    }

    return result;
  }

  /**
   * Add log entry
   */
  addLogEntry(entry, debugSource = null, aiDecisionContext = null) {
    // Merge debugSource and aiDecisionContext into the entry object
    const enhancedEntry = {
      ...entry,
      timestamp: entry.timestamp || Date.now(),
      round: entry.round || this.state.turn
    };

    // Add debugSource if provided
    if (debugSource) {
      enhancedEntry.debugSource = debugSource;
    }

    // Add aiDecisionContext if provided
    if (aiDecisionContext) {
      enhancedEntry.aiDecisionContext = aiDecisionContext;
    }

    const updatedLog = [...this.state.gameLog, enhancedEntry];
    this.setState({ gameLog: updatedLog }, 'LOG_ENTRY_ADDED');
  }

  /**
   * Add AI decision to history for CSV export
   * @param {string} phase - Decision phase (deployment, action, interception)
   * @param {number} turn - Turn number
   * @param {Array} possibleActions - Array of all evaluated actions
   * @param {Object} gameState - Current game state snapshot
   */
  addAIDecisionToHistory(phase, turn, possibleActions, gameState) {
    // Create decision entry
    const decisionEntry = {
      phase,
      turn,
      timestamp: new Date().toISOString(),
      decisions: possibleActions.map(action => ({
        type: action.type,
        instigator: action.instigator,
        targetName: action.targetName,
        score: action.score,
        logic: action.logic || [],
        isChosen: action.isChosen || false
      })),
      gameState: {
        player1: {
          energy: gameState?.player1?.energy,
          dronesOnBoard: gameState?.player1?.dronesOnBoard
        },
        player2: {
          energy: gameState?.player2?.energy,
          dronesOnBoard: gameState?.player2?.dronesOnBoard
        }
      }
    };

    const updatedHistory = [...this.state.aiDecisionHistory, decisionEntry];
    this.setState({ aiDecisionHistory: updatedHistory }, 'AI_DECISION_ADDED');
  }

  /**
   * Set winner
   * For single-player extraction mode, processes combat outcome (victory/defeat)
   */
  setWinner(winnerId) {
    // Check if this is single-player extraction mode combat
    const currentState = this.getState();
    if (currentState.gameMode === 'singlePlayer' && tacticalMapStateManager.isRunActive()) {
      debugLog('SP_COMBAT', `Single-player combat ended. Winner: ${winnerId}`);

      // Just set winner - WinnerModal will handle transition via button click
      // CombatOutcomeProcessor.processCombatEnd() is called from WinnerModal
      this.setState({ winner: winnerId }, 'GAME_ENDED');
      return;
    }

    // Standard multiplayer/local mode
    this.setState({ winner: winnerId }, 'GAME_ENDED');
  }

  // --- ACTION PROCESSING ---

  /**
   * Process a game action through the action queue
   * @param {string} actionType - Type of action (attack, ability, deployment, etc.)
   * @param {Object} payload - Action-specific data
   * @returns {Promise} Resolves when action is complete
   */
  async processAction(actionType, payload) {
    return await this.actionProcessor.queueAction({
      type: actionType,
      payload: payload
    });
  }

  /**
   * Check if any actions are currently being processed
   */
  isActionInProgress() {
    return this.actionProcessor.isActionInProgress();
  }

  /**
   * Get current action queue length
   */
  getActionQueueLength() {
    return this.actionProcessor.getQueueLength();
  }

  /**
   * Emergency action queue clear (use with caution)
   */
  clearActionQueue() {
    this.actionProcessor.clearQueue();
    // Re-establish GameFlowManager's subscription after clearQueue wipes listeners
    this.gameFlowManager?.resubscribe();
  }

  // --- SINGLE-PLAYER INVENTORY FACADES ---
  // External callers (EremosEntryScreen, SaveLoadModal, BlueprintsModal, RepairService) use these.
  // Delegation to singlePlayerInventoryManager.

  createNewSinglePlayerProfile() { this.singlePlayerInventoryManager.createNewSinglePlayerProfile(); }
  loadSinglePlayerSave(saveData) { this.singlePlayerInventoryManager.loadSinglePlayerSave(saveData); }
  getSaveData() { return this.singlePlayerInventoryManager.getSaveData(); }
  updateCardDiscoveryState(cardId, newState) { this.singlePlayerInventoryManager.updateCardDiscoveryState(cardId, newState); }
  addDiscoveredCard(cardId) { this.singlePlayerInventoryManager.addDiscoveredCard(cardId); }
  addToInventory(cardId, quantity = 1) { this.singlePlayerInventoryManager.addToInventory(cardId, quantity); }
  addShipComponentInstance(instance) { this.singlePlayerInventoryManager.addShipComponentInstance(instance); }
  updateShipComponentHull(instanceId, newHull) { this.singlePlayerInventoryManager.updateShipComponentHull(instanceId, newHull); }
  getShipComponentInstance(instanceId) { return this.singlePlayerInventoryManager.getShipComponentInstance(instanceId); }

  // --- TACTICAL ITEM FACADES ---
  // External callers (ShopModal, TacticalMapScreen, ExtractionController) use these.
  // Delegation to tacticalItemManager.

  purchaseTacticalItem(itemId) { return this.tacticalItemManager.purchaseTacticalItem(itemId); }
  purchaseCardPack() { return this.tacticalItemManager.purchaseCardPack(); }
  useTacticalItem(itemId) { return this.tacticalItemManager.useTacticalItem(itemId); }
  getTacticalItemCount(itemId) { return this.tacticalItemManager.getTacticalItemCount(itemId); }

  // ========================================
  // DECK MANAGEMENT METHODS
  // ========================================

  /**
   * Set default ship slot for deployment
   * @param {number} slotId - Slot ID (0-5)
   */
  setDefaultShipSlot(slotId) {
    if (slotId < 0 || slotId > 5) {
      throw new Error('Invalid slot ID: must be 0-5');
    }

    const slot = this.state.singlePlayerShipSlots.find(s => s.id === slotId);
    if (!slot || slot.status !== 'active') {
      throw new Error(`Slot ${slotId} is not active`);
    }

    const updatedProfile = {
      ...this.state.singlePlayerProfile,
      defaultShipSlotId: slotId
    };

    this.setState({ singlePlayerProfile: updatedProfile });
    debugLog('SP_SHIP', `Default ship slot set to ${slotId}`);
  }

  /**
   * Check if a deck slot is unlocked
   * @param {number} slotId - Slot ID (0-5)
   * @returns {boolean} True if slot is unlocked
   */
  isSlotUnlocked(slotId) {
    const highestUnlocked = this.state.singlePlayerProfile?.highestUnlockedSlot ?? 0;
    return slotId <= highestUnlocked;
  }

  /**
   * Get the next slot available for unlocking
   * @returns {Object|null} { slotId, cost } or null if all unlocked
   */
  getNextUnlockableSlot() {
    const highestUnlocked = this.state.singlePlayerProfile?.highestUnlockedSlot ?? 0;
    const nextSlotId = highestUnlocked + 1;
    if (nextSlotId > 5) return null;
    return {
      slotId: nextSlotId,
      cost: ECONOMY.DECK_SLOT_UNLOCK_COSTS[nextSlotId],
    };
  }

  /**
   * Unlock the next deck slot (sequential unlocking enforced)
   * Deducts credits from player profile
   * @returns {Object} { success: boolean, slotId?: number, error?: string }
   */
  unlockNextDeckSlot() {
    const profile = this.state.singlePlayerProfile;
    const currentHighest = profile.highestUnlockedSlot ?? 0;
    const nextSlotId = currentHighest + 1;

    // Check if all slots already unlocked
    if (nextSlotId > 5) {
      return { success: false, error: 'All deck slots are already unlocked' };
    }

    // Get cost for next slot
    const cost = ECONOMY.DECK_SLOT_UNLOCK_COSTS[nextSlotId];

    // Check if player has enough credits
    if (profile.credits < cost) {
      return {
        success: false,
        error: `Insufficient credits. Need ${cost}, have ${profile.credits}`,
      };
    }

    // Deduct credits and unlock slot
    const updatedProfile = {
      ...profile,
      credits: profile.credits - cost,
      highestUnlockedSlot: nextSlotId,
    };

    this.setState({ singlePlayerProfile: updatedProfile });
    debugLog('SP_SHIP', `Unlocked deck slot ${nextSlotId} for ${cost} credits`);
    return { success: true, slotId: nextSlotId };
  }

  /**
   * Save deck data to a ship slot
   * @param {number} slotId - Slot ID (1-5, cannot modify 0)
   * @param {Object} deckData - { name, decklist, droneSlots, drones, shipComponents, shipId }
   */
  saveShipSlotDeck(slotId, deckData) {
    if (slotId === 0) {
      throw new Error('Cannot modify Slot 0 (immutable starter deck)');
    }

    const { name, decklist, droneSlots, drones, shipComponents, shipId } = deckData;
    const slots = [...this.state.singlePlayerShipSlots];
    const slotIndex = slots.findIndex(s => s.id === slotId);

    if (slotIndex === -1) {
      throw new Error(`Slot ${slotId} not found`);
    }

    // Clear old instances for this slot
    this.clearSlotInstances(slotId);

    // Preserve existing sectionSlots OR convert from shipComponents
    // This ensures componentIds are properly populated for damage persistence
    let existingSectionSlots = slots[slotIndex].sectionSlots
      || convertComponentsToSectionSlots(shipComponents);

    // Update componentIds from shipComponents while preserving damageDealt
    if (shipComponents) {
      existingSectionSlots = { ...existingSectionSlots };
      Object.entries(shipComponents).forEach(([componentId, lane]) => {
        if (existingSectionSlots[lane]) {
          existingSectionSlots[lane] = {
            ...existingSectionSlots[lane],
            componentId
          };
        }
      });
    }

    slots[slotIndex] = {
      ...slots[slotIndex],
      name: name || `Ship ${slotId}`,
      decklist,
      // New format: droneSlots is the source of truth
      droneSlots: droneSlots || slots[slotIndex].droneSlots,
      // Legacy format for backward compatibility
      drones,
      shipComponents,
      sectionSlots: existingSectionSlots,
      shipId: shipId || null,
      status: 'active'
    };

    this.setState({ singlePlayerShipSlots: slots });
    debugLog('SP_SHIP', `Deck saved to slot ${slotId}`, { deckData });
  }

  /**
   * Delete deck from a ship slot, return cards to inventory
   * @param {number} slotId - Slot ID (1-5, cannot delete 0)
   */
  deleteShipSlotDeck(slotId) {
    if (slotId === 0) {
      throw new Error('Cannot delete Slot 0 (immutable starter deck)');
    }

    const slots = [...this.state.singlePlayerShipSlots];
    const slotIndex = slots.findIndex(s => s.id === slotId);

    if (slotIndex === -1) {
      throw new Error(`Slot ${slotId} not found`);
    }

    const slot = slots[slotIndex];
    if (slot.status !== 'active') {
      throw new Error(`Slot ${slotId} is not active`);
    }

    // Return non-starter-pool cards to inventory
    const newInventory = { ...this.state.singlePlayerInventory };
    (slot.decklist || []).forEach(card => {
      if (!starterPoolCards.includes(card.id)) {
        newInventory[card.id] = (newInventory[card.id] || 0) + card.quantity;
      }
    });

    // Clear instances for this slot
    this.clearSlotInstances(slotId);

    // Reset slot to empty state
    slots[slotIndex] = {
      id: slotId,
      name: `Ship Slot ${slotId}`,
      status: 'empty',
      isImmutable: false,
      decklist: [],
      // New format: empty drone slots
      droneSlots: [
        { slotIndex: 0, slotDamaged: false, assignedDrone: null },
        { slotIndex: 1, slotDamaged: false, assignedDrone: null },
        { slotIndex: 2, slotDamaged: false, assignedDrone: null },
        { slotIndex: 3, slotDamaged: false, assignedDrone: null },
        { slotIndex: 4, slotDamaged: false, assignedDrone: null }
      ],
      // Legacy format for backward compatibility
      drones: [],
      shipComponents: {},
      sectionSlots: {
        l: { componentId: null, damageDealt: 0 },
        m: { componentId: null, damageDealt: 0 },
        r: { componentId: null, damageDealt: 0 }
      }
    };

    // If this was the default slot, reset to 0
    let updatedProfile = this.state.singlePlayerProfile;
    if (updatedProfile.defaultShipSlotId === slotId) {
      updatedProfile = { ...updatedProfile, defaultShipSlotId: 0 };
    }

    this.setState({
      singlePlayerShipSlots: slots,
      singlePlayerInventory: newInventory,
      singlePlayerProfile: updatedProfile
    });

    debugLog('SP_SHIP', `Deck deleted from slot ${slotId}, cards returned to inventory`);
  }

  /**
   * Clear drone and component instances for a slot
   * @param {number} slotId - Slot ID
   */
  clearSlotInstances(slotId) {
    const droneInstances = this.state.singlePlayerDroneInstances.filter(
      i => i.shipSlotId !== slotId
    );
    const componentInstances = this.state.singlePlayerShipComponentInstances.filter(
      i => i.shipSlotId !== slotId
    );

    this.setState({
      singlePlayerDroneInstances: droneInstances,
      singlePlayerShipComponentInstances: componentInstances
    });
  }

  /**
   * Update drone slot order for a ship slot (for Repair Bay reordering)
   * Swaps only assignedDrone values; slotDamaged stays with the slot position
   * @param {number} slotId - Ship slot ID (0-5)
   * @param {Array} newDroneSlots - Updated drone slots array
   */
  updateShipSlotDroneOrder(slotId, newDroneSlots) {
    const slots = [...this.state.singlePlayerShipSlots];
    const slotIndex = slots.findIndex(s => s.id === slotId);

    if (slotIndex === -1) {
      debugLog('SP_SHIP', `⚠️ updateShipSlotDroneOrder: Slot ${slotId} not found`);
      return;
    }

    // Update the drone slots
    slots[slotIndex] = {
      ...slots[slotIndex],
      droneSlots: newDroneSlots
    };

    this.setState({ singlePlayerShipSlots: slots });
    debugLog('STATE_SYNC', `Drone order updated for slot ${slotId}`);
  }

  /**
   * Repair a damaged drone slot
   * @param {number} slotId - Ship slot ID (1-5, cannot modify 0)
   * @param {number} position - Drone slot position (0-4)
   * @returns {Object} { success, reason? }
   */
  repairDroneSlot(slotId, position) {
    if (slotId === 0) {
      return { success: false, reason: 'Cannot modify Slot 0 (immutable starter deck)' };
    }

    const slots = [...this.state.singlePlayerShipSlots];
    const slotIndex = slots.findIndex(s => s.id === slotId);

    if (slotIndex === -1) {
      return { success: false, reason: `Slot ${slotId} not found` };
    }

    const slot = slots[slotIndex];
    if (!slot.droneSlots?.[position]) {
      return { success: false, reason: `Drone position ${position} not found` };
    }

    // Support both old (isDamaged) and new (slotDamaged) field names
    const droneSlot = slot.droneSlots[position];
    const isCurrentlyDamaged = droneSlot.slotDamaged ?? droneSlot.isDamaged ?? false;

    if (!isCurrentlyDamaged) {
      return { success: false, reason: 'Drone slot is not damaged' };
    }

    const cost = ECONOMY.DRONE_SLOT_REPAIR_COST || 50;
    const profile = { ...this.state.singlePlayerProfile };

    if (profile.credits < cost) {
      return { success: false, reason: `Insufficient credits. Need ${cost}, have ${profile.credits}` };
    }

    // Deduct credits
    profile.credits -= cost;

    // Repair the slot (set both old and new field names for compatibility)
    slots[slotIndex] = {
      ...slot,
      droneSlots: slot.droneSlots.map((ds, i) =>
        i === position ? { ...ds, slotDamaged: false, isDamaged: false } : ds
      )
    };

    this.setState({
      singlePlayerShipSlots: slots,
      singlePlayerProfile: profile
    });

    debugLog('SP_REPAIR', `Repaired drone slot ${position} in ship slot ${slotId} for ${cost} credits`);
    return { success: true };
  }

  /**
   * Repair a damaged section slot (fully repairs all damage)
   * @param {number} slotId - Ship slot ID (1-5, cannot modify 0)
   * @param {string} lane - Lane key ('l', 'm', or 'r')
   * @returns {Object} { success, reason? }
   */
  repairSectionSlot(slotId, lane) {
    if (slotId === 0) {
      return { success: false, reason: 'Cannot modify Slot 0 (immutable starter deck)' };
    }

    const slots = [...this.state.singlePlayerShipSlots];
    const slotIndex = slots.findIndex(s => s.id === slotId);

    if (slotIndex === -1) {
      return { success: false, reason: `Slot ${slotId} not found` };
    }

    const slot = slots[slotIndex];
    if (!slot.sectionSlots?.[lane]) {
      return { success: false, reason: `Lane ${lane} not found` };
    }

    const damageDealt = slot.sectionSlots[lane].damageDealt || 0;
    if (damageDealt <= 0) {
      return { success: false, reason: 'Section is not damaged' };
    }

    const costPerDamage = ECONOMY.SECTION_DAMAGE_REPAIR_COST || 10;
    const cost = damageDealt * costPerDamage;
    const profile = { ...this.state.singlePlayerProfile };

    if (profile.credits < cost) {
      return { success: false, reason: `Insufficient credits. Need ${cost}, have ${profile.credits}` };
    }

    // Deduct credits
    profile.credits -= cost;

    // Repair the section (set damageDealt to 0)
    slots[slotIndex] = {
      ...slot,
      sectionSlots: {
        ...slot.sectionSlots,
        [lane]: { ...slot.sectionSlots[lane], damageDealt: 0 }
      }
    };

    this.setState({
      singlePlayerShipSlots: slots,
      singlePlayerProfile: profile
    });

    debugLog('SP_REPAIR', `Repaired section ${lane} in ship slot ${slotId} for ${cost} credits (${damageDealt} damage)`);
    return { success: true };
  }

  /**
   * Repair a section slot partially (incremental repair)
   * @param {number} slotId - Ship slot ID (1-5)
   * @param {string} lane - Lane identifier ('l', 'm', 'r')
   * @param {number} hpToRepair - Amount of HP to repair (default 1)
   * @returns {{ success: boolean, reason?: string, cost?: number, repairedHP?: number, remainingDamage?: number }}
   */
  repairSectionSlotPartial(slotId, lane, hpToRepair = 1) {
    if (slotId === 0) {
      return { success: false, reason: 'Cannot modify Slot 0 (immutable starter deck)' };
    }

    if (hpToRepair < 1) {
      return { success: false, reason: 'Must repair at least 1 HP' };
    }

    const slots = [...this.state.singlePlayerShipSlots];
    const slotIndex = slots.findIndex(s => s.id === slotId);

    if (slotIndex === -1) {
      return { success: false, reason: `Slot ${slotId} not found` };
    }

    const slot = slots[slotIndex];
    if (!slot.sectionSlots?.[lane]) {
      return { success: false, reason: `Lane ${lane} not found` };
    }

    const damageDealt = slot.sectionSlots[lane].damageDealt || 0;
    if (damageDealt <= 0) {
      return { success: false, reason: 'Section is not damaged' };
    }

    // Cap repair amount to actual damage
    const actualRepair = Math.min(hpToRepair, damageDealt);
    const costPerDamage = ECONOMY.SECTION_DAMAGE_REPAIR_COST || 200;
    const cost = actualRepair * costPerDamage;
    const profile = { ...this.state.singlePlayerProfile };

    if (profile.credits < cost) {
      return { success: false, reason: `Insufficient credits. Need ${cost}, have ${profile.credits}` };
    }

    // Deduct credits
    profile.credits -= cost;

    // Reduce damage (partial repair)
    const newDamage = damageDealt - actualRepair;
    slots[slotIndex] = {
      ...slot,
      sectionSlots: {
        ...slot.sectionSlots,
        [lane]: { ...slot.sectionSlots[lane], damageDealt: newDamage }
      }
    };

    this.setState({
      singlePlayerShipSlots: slots,
      singlePlayerProfile: profile
    });

    debugLog('SP_REPAIR', `Partial repair: ${actualRepair} HP on section ${lane} in slot ${slotId} for ${cost} credits (${newDamage} damage remaining)`);
    return {
      success: true,
      cost,
      repairedHP: actualRepair,
      remainingDamage: newDamage
    };
  }

  /**
   * Create a drone instance for tracking damage
   * Only for non-starter-pool drones
   * @param {string} droneName - Name of the drone
   * @param {number} slotId - Ship slot ID
   * @returns {string|null} Instance ID or null if starter pool drone
   */
  createDroneInstance(droneName, slotId) {
    // Starter pool drones don't need instances (never damaged)
    if (starterPoolDroneNames.includes(droneName)) {
      return null;
    }

    const instanceId = `DRONE_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    const instance = {
      instanceId,
      droneName,
      shipSlotId: slotId,
      isDamaged: false
    };

    const instances = [...this.state.singlePlayerDroneInstances, instance];
    this.setState({ singlePlayerDroneInstances: instances });

    debugLog('SP_DRONE', `Created drone instance: ${instanceId} for ${droneName}`);
    return instanceId;
  }

  /**
   * Update drone instance damage state
   * @param {string} instanceId - Instance ID
   * @param {boolean} isDamaged - New damage state
   */
  updateDroneInstance(instanceId, isDamaged) {
    const instances = [...this.state.singlePlayerDroneInstances];
    const index = instances.findIndex(inst => inst.instanceId === instanceId);

    if (index >= 0) {
      instances[index] = { ...instances[index], isDamaged };
      this.setState({ singlePlayerDroneInstances: instances });
      debugLog('SP_DRONE', `Drone instance ${instanceId} damage updated to ${isDamaged}`);
    } else {
      debugLog('SP_DRONE', `⚠️ Drone instance ${instanceId} not found`);
    }
  }

  /**
   * Find drone instance by slot ID and drone name
   * @param {number} slotId - Ship slot ID
   * @param {string} droneName - Drone name
   * @returns {Object|null} Drone instance or null if not found
   */
  findDroneInstance(slotId, droneName) {
    return this.state.singlePlayerDroneInstances.find(
      inst => inst.shipSlotId === slotId && inst.droneName === droneName
    ) || null;
  }

  /**
   * Get damage state for all drones in a specific slot
   * Returns a map of drone name -> isDamaged boolean
   * Slot 0 always returns empty object (starter deck never persists damage)
   * @param {number} slotId - Ship slot ID
   * @returns {Object} Map of drone name to damage state
   */
  getDroneDamageStateForSlot(slotId) {
    // Slot 0 (starter deck) never has persisted damage
    if (slotId === 0) {
      return {};
    }

    const damageState = {};
    this.state.singlePlayerDroneInstances
      .filter(inst => inst.shipSlotId === slotId)
      .forEach(inst => {
        damageState[inst.droneName] = inst.isDamaged || false;
      });

    return damageState;
  }

  /**
   * Create a ship component instance for tracking hull damage
   * Only for non-starter-pool components
   * @param {string} componentId - Component ID
   * @param {number} slotId - Ship slot ID
   * @returns {string|null} Instance ID or null if starter pool component
   */
  createComponentInstance(componentId, slotId) {
    // Starter pool components don't need instances (never damaged)
    if (starterPoolCards.includes(componentId)) {
      return null;
    }

    const component = shipComponentCollection.find(c => c.id === componentId);
    if (!component) {
      throw new Error(`Component ${componentId} not found`);
    }

    const instanceId = `COMP_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    const instance = {
      instanceId,
      componentId,
      shipSlotId: slotId,
      currentHull: component.hull,
      maxHull: component.maxHull || component.hull
    };

    const instances = [...this.state.singlePlayerShipComponentInstances, instance];
    this.setState({ singlePlayerShipComponentInstances: instances });

    debugLog('SP_DRONE', `Created component instance: ${instanceId} for ${componentId}`);
    return instanceId;
  }

  /**
   * Start extraction run
   * @param {number} shipSlotId - Ship slot ID to use (0-5)
   * @param {number} mapTier - Map tier (1-3)
   * @param {number} entryGateId - Selected entry gate ID (0-indexed)
   * @param {Object} preGeneratedMap - Optional pre-generated map data from Hangar preview
   * @param {Object} quickDeploy - Optional quick deploy template to use for first combat
   */
  startRun(shipSlotId, mapTier, entryGateId = 0, preGeneratedMap = null, quickDeploy = null) {
    debugLog('EXTRACTION', '=== START RUN ===', {
      shipSlotId,
      mapTier,
      entryGateId,
      hasPreGeneratedMap: !!preGeneratedMap,
      hasQuickDeploy: !!quickDeploy,
      currentAppState: this.state.appState,
      hasExistingRun: tacticalMapStateManager.isRunActive(),
      runAbandoning: this.state.runAbandoning
    });

    const shipSlot = this.state.singlePlayerShipSlots.find(s => s.id === shipSlotId);
    if (!shipSlot) {
      throw new Error('Invalid ship slot ID');
    }

    if (shipSlot.status !== 'active') {
      throw new Error(`Ship slot ${shipSlotId} is not active (status: ${shipSlot.status})`);
    }

    // Get ship card for proper hull/threshold calculation
    // Uses ship's baseHull + section's hullModifier instead of deprecated absolute values
    const shipCard = shipSlot?.shipId
      ? getAllShips().find(s => s.id === shipSlot.shipId)
      : getDefaultShip();

    // Use pre-generated map if provided (from Hangar preview), otherwise generate new
    let mapData;
    if (preGeneratedMap && preGeneratedMap.hexes) {
      mapData = preGeneratedMap;
    } else {
      // Fallback: Generate map using deterministic seed
      const seed = Date.now(); // TODO: Use profile-based seed for reproducibility
      const mapType = 'GENERIC'; // TODO: Support map type selection in Phase 4+
      mapData = generateMapData(seed, mapTier, mapType);
    }

    // Deduct security token if map requires it
    if (mapData.requiresToken) {
      const currentTokens = this.state.singlePlayerProfile?.securityTokens || 0;
      if (currentTokens < 1) {
        debugLog('EXTRACTION', '🚨 Cannot start run - insufficient tokens');
        return;
      }

      // Deduct token
      this.setState({
        singlePlayerProfile: {
          ...this.state.singlePlayerProfile,
          securityTokens: currentTokens - 1
        }
      });
      debugLog('EXTRACTION', `Deducted 1 security token. Remaining: ${currentTokens - 1}`);
    }

    // Set player starting position to selected entry gate
    const startingGate = mapData.gates[entryGateId] || mapData.gates[0];

    // Build per-section hull tracking from ship slot components
    // Uses slot-based damage model: damage is stored in sectionSlots, not instances
    const runShipSections = {};
    let totalHull = 0;
    let maxHull = 0;

    // Helper to normalize component type to lowercase camelCase key
    // This ensures consistency with CombatOutcomeProcessor and SinglePlayerCombatInitializer
    // which expect keys like 'bridge', 'powerCell', 'droneControlHub'
    const normalizeTypeToKey = (type) => {
      const typeToKey = {
        'Bridge': 'bridge',
        'Power Cell': 'powerCell',
        'Drone Control Hub': 'droneControlHub'
      };
      return typeToKey[type] || type.charAt(0).toLowerCase() + type.slice(1).replace(/\s+/g, '');
    };

    // Use new slot-based format if available, fall back to legacy
    if (shipSlot?.sectionSlots) {
      // New slot-based format: { l: { componentId, damageDealt }, m: {...}, r: {...} }
      const laneNames = { l: 'left', m: 'middle', r: 'right' };

      Object.entries(shipSlot.sectionSlots).forEach(([lane, sectionSlot]) => {
        if (!sectionSlot?.componentId) return;

        const component = shipComponentCollection.find(c => c.id === sectionSlot.componentId);
        if (component) {
          // Calculate base stats using ship card + section modifiers (correct approach)
          const baseStats = calculateSectionBaseStats(shipCard, component);
          const componentMaxHull = baseStats.maxHull;
          const damageDealt = sectionSlot.damageDealt || 0;

          // For slot 0 (starter deck), ignore any damage
          const hullValue = (shipSlotId === 0)
            ? componentMaxHull
            : Math.max(0, componentMaxHull - damageDealt);

          // Use normalized lowercase key for consistency with CombatOutcomeProcessor
          const sectionKey = normalizeTypeToKey(component.type);
          runShipSections[sectionKey] = {
            id: sectionSlot.componentId,
            name: component.name,
            type: component.type,
            hull: hullValue,
            maxHull: componentMaxHull,
            thresholds: baseStats.thresholds,
            lane: lane
          };
          totalHull += hullValue;
          maxHull += componentMaxHull;
        }
      });
    } else if (shipSlot?.shipComponents) {
      // Legacy format fallback: { componentId: lane }
      Object.entries(shipSlot.shipComponents).forEach(([componentId, lane]) => {
        const component = shipComponentCollection.find(c => c.id === componentId);
        if (component) {
          // Calculate base stats using ship card + section modifiers (correct approach)
          const baseStats = calculateSectionBaseStats(shipCard, component);
          const componentMaxHull = baseStats.maxHull;

          // Use normalized lowercase key for consistency with CombatOutcomeProcessor
          const sectionKey = normalizeTypeToKey(component.type);
          runShipSections[sectionKey] = {
            id: componentId,
            name: component.name,
            type: component.type,
            hull: componentMaxHull,
            maxHull: componentMaxHull,
            thresholds: baseStats.thresholds,
            lane: lane
          };
          totalHull += componentMaxHull;
          maxHull += componentMaxHull;
        }
      });
    }

    // Fallback to default sections if no components defined
    // Uses ship card values instead of hardcoded 10/10
    // Keys use lowercase camelCase for consistency with CombatOutcomeProcessor
    if (Object.keys(runShipSections).length === 0) {
      const defaultThresholds = shipCard?.baseThresholds || { damaged: 4, critical: 0 };
      const defaultHull = shipCard?.baseHull || 8;

      runShipSections.bridge = { type: 'Bridge', hull: defaultHull, maxHull: defaultHull, thresholds: defaultThresholds, lane: 'm' };
      runShipSections.powerCell = { type: 'Power Cell', hull: defaultHull, maxHull: defaultHull, thresholds: defaultThresholds, lane: 'l' };
      runShipSections.droneControlHub = { type: 'Drone Control Hub', hull: defaultHull, maxHull: defaultHull, thresholds: defaultThresholds, lane: 'r' };
      totalHull = defaultHull * 3;
      maxHull = defaultHull * 3;
    }

    const runState = {
      shipSlotId,
      mapTier,
      detection: mapData.baseDetection || 0,  // Use map's starting detection
      playerPosition: startingGate,
      // Track insertion gate separately (gates[0] = entry, gates[1+] = extraction)
      insertionGate: { q: startingGate.q, r: startingGate.r },
      collectedLoot: [],
      creditsEarned: 0,
      mapData,
      // Per-section hull tracking for damage persistence across combats
      shipSections: runShipSections,
      currentHull: totalHull,
      maxHull: maxHull,

      // Run statistics tracking
      runStartTime: Date.now(),
      hexesMoved: 0,
      hexesExplored: [{ q: startingGate.q, r: startingGate.r }], // Start with insertion gate
      poisVisited: [],
      lootedPOIs: [],  // Track POIs that have been looted (prevents re-looting)
      fledPOIs: [],  // Track POIs where player fled/escaped (escape or evade)
      highAlertPOIs: [],  // Track POIs in high alert state after combat victory (increased encounter chance)
      combatsWon: 0,
      combatsLost: 0,
      damageDealtToEnemies: 0,

      // Quick deploy for first combat (consumed after use)
      pendingQuickDeploy: quickDeploy || null,

      // Blockade flags - MUST be initialized false for fresh runs
      // These track post-blockade extraction state and must not persist across runs
      pendingBlockadeExtraction: false,
      blockadeCleared: false,
    };

    debugLog('MODE_TRANSITION', '=== MODE: hangar -> tacticalMap ===', {
      trigger: 'async_event',
      source: 'GameStateManager.startRun',
      detail: 'Deploying screen completed, run initialized',
      shipSlotId,
      mapTier,
      mapName: mapData.name
    });

    // Initialize TacticalMapStateManager with run data
    // This provides clean separation of tactical map state from combat state
    tacticalMapStateManager.startRun({
      shipSlotId,
      mapTier,
      mapData,
      startingGate,
      shipSections: runShipSections
    });
    debugLog('STATE_SYNC', 'TacticalMapStateManager initialized for run');

    this.setState({
      appState: 'tacticalMap',
      // CRITICAL: Clear stale flags from previous runs to prevent race conditions
      // runAbandoning must be false or SinglePlayerCombatInitializer will reject combat init
      runAbandoning: false,
    });

    // CRITICAL: Reset TransitionManager to clear any stale transition state from previous runs
    // This prevents "Transition already in progress" errors when entering combat
    transitionManager.forceReset();

    debugLog('EXTRACTION', 'Run started via TacticalMapStateManager');
    debugLog('EXTRACTION', `Map generated: ${mapData.name} (${mapData.poiCount} PoIs, ${mapData.gateCount} gates)`);
  }

  /**
   * Reset game state to pre-game defaults
   * Used when abandoning mid-combat or exiting games to ensure clean state
   * This is the SINGLE SOURCE OF TRUTH for combat state cleanup
   */
  resetGameState() {
    debugLog('SP_COMBAT', '=== RESET GAME STATE ===');

    // Set context to GameFlowManager since resetGameState legitimately resets
    // game orchestration state (this avoids ownership violations when called
    // from CombatOutcomeProcessor.finalizeLootCollection or other paths)
    this._updateContext = 'GameFlowManager';

    try {
      this.setState({
        // Game flow state
        gameActive: false,
        testMode: false,
        gameSeed: null,
        turnPhase: null,
        gameStage: 'preGame',
        roundNumber: 0,
        turn: 1,
        currentPlayer: 'player1',
        actionsTakenThisTurn: 0,
        firstPlayerOfRound: null,
        firstPasserOfPreviousRound: null,
        firstPlayerOverride: null,

        // Player states
        player1: null,
        player2: null,

        // Pass state
        passInfo: {
          firstPasser: null,
          player1Passed: false,
          player2Passed: false
        },

        // Combat state
        attackInProgress: null,
        lastCombatResult: null,
        winner: null,
        singlePlayerEncounter: null,

        // UI state - ship placement
        placedSections: [],
        opponentPlacedSections: [],
        unplacedSections: [],

        // UI state - game
        gameLog: [],
        commitments: {},
        shieldsToAllocate: 0,
        opponentShieldsToAllocate: 0,

        // Drone selection state
        droneSelectionPool: [],
        droneSelectionTrio: []
      }, 'GAME_STATE_RESET');

      // Reset singletons to ensure clean state for next combat
      // These are idempotent - safe to call multiple times

      // GameFlowManager - reset phase/stage tracking
      if (this.gameFlowManager?.reset) {
        this.gameFlowManager.reset();
        debugLog('SP_COMBAT', '✅ GameFlowManager reset');
      }

      // ActionProcessor - clear queue and locks
      if (this.actionProcessor?.clearQueue) {
        this.actionProcessor.clearQueue();
        // Re-establish GameFlowManager's subscription after clearQueue wipes listeners
        this.gameFlowManager?.resubscribe();
        debugLog('SP_COMBAT', '✅ ActionProcessor queue cleared');
      }

      // AIPhaseProcessor - cleanup subscriptions and timers
      if (aiPhaseProcessor?.cleanup) {
        aiPhaseProcessor.cleanup();
        debugLog('SP_COMBAT', '✅ AIPhaseProcessor cleaned up');
      }
    } finally {
      this._updateContext = null;
    }
  }

  /**
   * End extraction run
   * @param {boolean} success - True if successful extraction, false if MIA
   */
  endRun(success = true) {
    debugLog('SP_COMBAT', '=== END RUN CALLED ===', {
      success,
      currentAppState: this.state.appState,
      currentTurnPhase: this.state.turnPhase,
      currentGameActive: this.state.gameActive,
      currentGameStage: this.state.gameStage,
      hasPlayer1: !!this.state.player1,
      hasPlayer2: !!this.state.player2
    });

    // Read run state from TacticalMapStateManager
    const runState = tacticalMapStateManager.getState();
    if (!runState) {
      debugLog('EXTRACTION', '⚠️ No active run to end');
      debugLog('SP_COMBAT', 'WARNING: No active run to end');
      return;
    }

    // Generate run summary BEFORE clearing state
    const hexesExploredCount = runState.hexesExplored?.length || 0;
    const totalHexes = runState.mapData?.hexes?.length || 1;
    const runDuration = Date.now() - (runState.runStartTime || Date.now());

    // Get full card data for collected cards
    const cardsCollected = (runState.collectedLoot || [])
      .filter(item => item.type === 'card')
      .map(item => {
        const fullCard = fullCardCollection.find(c => c.id === item.cardId);
        return fullCard ? { ...fullCard, source: item.source } : null;
      })
      .filter(Boolean);

    // Get blueprint data for collected blueprints
    const blueprintsCollected = (runState.collectedLoot || [])
      .filter(item => item.type === 'blueprint')
      .map(item => ({
        blueprintId: item.blueprintId,
        blueprintType: item.blueprintType || 'drone',
        rarity: item.rarity,
        droneData: item.droneData
      }));

    // Calculate credits from salvage items in collectedLoot (not legacy creditsEarned)
    const extractedCredits = calculateExtractedCredits(runState.collectedLoot || []);

    const lastRunSummary = {
      success,
      mapName: runState.mapData?.name || 'Unknown Sector',
      mapTier: runState.mapTier || 1,

      // Movement & Exploration
      hexesMoved: runState.hexesMoved || 0,
      hexesExplored: hexesExploredCount,
      totalHexes,
      mapCompletionPercent: ((hexesExploredCount / totalHexes) * 100).toFixed(1),

      // POIs & Loot
      poisVisited: runState.poisVisited?.length || 0,
      totalPois: runState.mapData?.poiCount || 0,
      cardsCollected, // Full card objects for display
      blueprintsCollected, // Drone blueprints unlocked this run
      creditsEarned: extractedCredits, // Calculated from salvage items
      aiCoresEarned: runState.aiCoresEarned || 0,

      // Combat
      combatsWon: runState.combatsWon || 0,
      combatsLost: runState.combatsLost || 0,
      damageDealtToEnemies: runState.damageDealtToEnemies || 0,

      // Ship Status
      hullDamageTaken: (runState.maxHull || 0) - (runState.currentHull || 0),
      finalHull: runState.currentHull || 0,
      maxHull: runState.maxHull || 0,

      // Time
      runDuration,

      // Detection
      finalDetection: runState.detection || 0,
    };

    debugLog('EXTRACTION', 'Run summary generated', { lastRunSummary });

    // Build all state changes immutably, then apply via setState at the end
    const newInventory = { ...this.state.singlePlayerInventory };
    const newProfile = {
      ...this.state.singlePlayerProfile,
      stats: { ...this.state.singlePlayerProfile.stats }
    };
    let newShipSlots = [...this.state.singlePlayerShipSlots];

    if (success) {
      // Transfer loot to inventory
      const newBlueprints = [...(newProfile.unlockedBlueprints || [])];
      runState.collectedLoot.forEach(item => {
        if (item.type === 'card') {
          newInventory[item.cardId] = (newInventory[item.cardId] || 0) + 1;
        } else if (item.type === 'blueprint') {
          if (!newBlueprints.includes(item.blueprintId)) {
            newBlueprints.push(item.blueprintId);
          }
        }
      });
      newProfile.unlockedBlueprints = newBlueprints;

      // Add credits (calculated from salvage items, not legacy creditsEarned)
      newProfile.credits += extractedCredits;

      // Add AI Cores earned from combat
      newProfile.aiCores = (newProfile.aiCores || 0) + (runState.aiCoresEarned || 0);

      // Update statistics
      newProfile.stats.runsCompleted++;
      newProfile.stats.totalCreditsEarned += extractedCredits;
      newProfile.stats.totalCombatsWon =
        (newProfile.stats.totalCombatsWon || 0) + (runState.combatsWon || 0);

      // Track highest tier completed
      const currentTier = runState.mapTier || 1;
      if (currentTier > (newProfile.stats.highestTierCompleted || 0)) {
        newProfile.stats.highestTierCompleted = currentTier;
      }

      // Refresh shop pack for next hangar visit (uses updated highestTierCompleted)
      const highestTier = newProfile.stats.highestTierCompleted || 0;
      newProfile.shopPack = generateRandomShopPack(highestTier, Date.now());
      debugLog('EXTRACTION', 'Shop pack refreshed', { shopPack: newProfile.shopPack });

      debugLog('EXTRACTION', 'Run ended successfully - loot transferred');

      // Persist ship section hull damage using slot-based format
      if (runState.shipSlotId !== 0 && runState.shipSections) {
        const slotIndex = newShipSlots.findIndex(s => s.id === runState.shipSlotId);

        if (slotIndex >= 0 && newShipSlots[slotIndex].sectionSlots) {
          const shipSlot = { ...newShipSlots[slotIndex] };
          const newSectionSlots = { ...shipSlot.sectionSlots };

          Object.entries(runState.shipSections).forEach(([sectionName, sectionData]) => {
            const lane = sectionData.lane;
            if (lane && newSectionSlots[lane]) {
              const damageDealt = (sectionData.maxHull || 10) - (sectionData.hull || 0);
              newSectionSlots[lane] = {
                ...newSectionSlots[lane],
                damageDealt: Math.max(0, damageDealt)
              };
            }
          });

          shipSlot.sectionSlots = newSectionSlots;
          newShipSlots[slotIndex] = shipSlot;
          debugLog('EXTRACTION', 'Ship section hull damage persisted to sectionSlots');
        }
      }
    } else {
      // MIA: Wipe loot, mark slot
      // Slot 0 (Starter Deck) never goes MIA - player just loses loot
      if (runState.shipSlotId !== 0) {
        const slotIndex = newShipSlots.findIndex(s => s.id === runState.shipSlotId);
        if (slotIndex >= 0) {
          newShipSlots[slotIndex] = { ...newShipSlots[slotIndex], status: 'mia' };
        }
      }

      // Update statistics
      newProfile.stats.runsLost++;

      debugLog('EXTRACTION', 'Run ended - MIA protocol triggered');
    }

    // Calculate total combat reputation from run
    const combatReputationArray = runState.combatReputationEarned || [];
    const totalCombatRep = combatReputationArray.reduce((sum, entry) => sum + entry.repEarned, 0);

    debugLog('REPUTATION', 'Combat reputation summary:', {
      combatCount: combatReputationArray.length,
      totalCombatRep,
      breakdown: combatReputationArray
    });

    // Award reputation based on loadout value + combat reputation
    const shipSlot = newShipSlots.find(s => s.id === runState.shipSlotId);
    const reputationResult = ReputationService.awardReputation(
      shipSlot,
      runState.mapTier || 1,
      success,
      totalCombatRep
    );

    // Add reputation info to run summary
    lastRunSummary.reputation = {
      repGained: reputationResult.repGained || 0,
      loadoutRepGained: reputationResult.loadoutRepGained || 0,
      combatRepGained: reputationResult.combatRepGained || 0,
      previousRep: reputationResult.previousRep || 0,
      newRep: reputationResult.newRep || 0,
      previousLevel: reputationResult.previousLevel || 1,
      newLevel: reputationResult.newLevel || 1,
      leveledUp: reputationResult.leveledUp || false,
      levelsGained: reputationResult.levelsGained || 0,
      newRewards: reputationResult.newRewards || [],
      loadoutValue: reputationResult.loadout?.totalValue || 0,
      isStarterDeck: reputationResult.loadout?.isStarterDeck || false,
      wasCapped: reputationResult.wasCapped || false,
      tierCap: reputationResult.tierCap || 0,
    };

    debugLog('EXTRACTION', 'Reputation awarded', { reputation: lastRunSummary.reputation });

    // End the run in TacticalMapStateManager
    tacticalMapStateManager.endRun();
    debugLog('STATE_SYNC', 'TacticalMapStateManager run ended');

    // Apply all state changes via setState so subscribers are notified
    this.setState({
      lastRunSummary,
      singlePlayerProfile: newProfile,
      singlePlayerInventory: newInventory,
      singlePlayerShipSlots: newShipSlots,
    });

    debugLog('SP_COMBAT', '=== END RUN COMPLETE ===', {
      clearedRunState: !tacticalMapStateManager.isRunActive(),
      // Note: game state (player1, player2, gameActive) is NOT cleared by endRun
      gameActiveStillSet: this.state.gameActive,
      turnPhaseStillSet: this.state.turnPhase,
      hasPlayer1StillSet: !!this.state.player1,
      hasPlayer2StillSet: !!this.state.player2
    });
  }
}

// Create singleton instance
const gameStateManager = new GameStateManager();

// Preserve singleton across Hot Module Replacement (HMR) in development
// This prevents state loss during development when files are edited
if (import.meta.hot) {
  import.meta.hot.accept();
  // Store the current instance in HMR data to preserve across reloads
  if (import.meta.hot.data?.gameStateManager) {
    // Restore the previous instance's state
    gameStateManager.state = import.meta.hot.data.gameStateManager.state;
    gameStateManager.listeners = import.meta.hot.data.gameStateManager.listeners;
    debugLog('STATE_SYNC', '🔄 HMR: Preserved GameStateManager state across hot reload');
  }
  import.meta.hot.dispose((data) => {
    // Store instance before disposing
    data.gameStateManager = gameStateManager;
  });
}

export default gameStateManager;